#!/bin/sh
# Generator for the hash list.
# This is unquestionably magic.
set -e
cat <<HEADER
%{
// THIS FILE IS GENERATED BY src/gen_list.sh.
// DO NOT TOUCH HERE.
%}
struct emoji_ref { char* name; unsigned int ref; };
%%
HEADER

cat gen/emoji.csv | sed 's/"//g' | \
	awk -F',' '{ count++; for (i = 2; i <= NF; i++) printf "%s, %i\n", $i, count;}'
